-- 1. Tạo bảng lưu trữ Upload (Mapping tên file và ID)
create table public.sora_uploads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  file_name text not null,          -- Tên file gốc (ví dụ: my-image.png)
  file_id text,                     -- ID trả về từ API Upload (nếu có)
  upload_media_id text,             -- ID quan trọng dùng cho Remix (media_xyz...)
  file_url text                -- Lưu toàn bộ phản hồi API để debug
);

-- 2. Tạo bảng lưu trữ Task (Lịch sử tạo ảnh/video)
create table public.sora_tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  prompt text,
  status text,                      -- Trạng thái: COMPLETED, FAILED...
  config jsonb,                     -- Cấu hình lúc chạy: { width, height, n_variants... }
  result_urls text,                -- Kết quả trả về (URL ảnh/video...)
  error_message text                -- Lỗi nếu có
);

-- 3. Bật Row Level Security (RLS) - Tùy chọn nhưng khuyến khích
alter table public.sora_uploads enable row level security;
alter table public.sora_tasks enable row level security;

-- 4. Tạo Policy cho phép mọi người (Anon) Đọc và Ghi
-- Lưu ý: Để đơn giản cho demo, ta cho phép anon truy cập. 
-- Trong thực tế production nên hạn chế quyền này.

-- Policy cho Uploads
create policy "Enable read access for all users" on public.sora_uploads for select using (true);
create policy "Enable insert access for all users" on public.sora_uploads for insert with check (true);

-- Policy cho Tasks
create policy "Enable read access for all users" on public.sora_tasks for select using (true);
create policy "Enable insert access for all users" on public.sora_tasks for insert with check (true);